source 'https://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@github.com/MMSuperD/FANSpec.git'
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


platform :ios, '11.0'

target 'FANOCBaseConfig_Example' do
  pod 'FANOCBaseConfig', :path => '../'

  target 'FANOCBaseConfig_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
