use_frameworks!

platform :ios, '9.0'

target 'FANOCBaseConfig_Example' do
  pod 'FANOCBaseConfig', :path => '../'

  target 'FANOCBaseConfig_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
